language: java
jdk: openjdk8
cache:
  directories:
  - "$HOME/.m2"
before_cache:
- rm -rf $HOME/.m2/repository/com/skillsforge
jobs:
  include:
  - stage: test
    script: mvn -q clean test
  - stage: deploy
    if: tag IS present
    script: mvn -q clean install && mkdir -p target/deploy && cp target/account-feed-utility-$TRAVIS_TAG.jar target/deploy/
    deploy:
      provider: s3
      skip_cleanup: true
      access_key_id: AKIAI2DBR6XXN66BKUSQ
      secret_access_key:
        secure: Dnc+t0S9weDXDKH6TUgWY2HTsf8rehHljtTXEWptaTENOpmmPayu9xgPJmexma0XwSadwgRK0rQasazjXcXxB/DuKeKkBcujDykECCfS0prfbY6pmsdhHFalIcjwWARoqXh/Xp4d8PFWLbMDQVGnPbsCuGsUeng0dE4h1TWIoV+NUkiKG0Hnlrb3/zL7JroANd29QsfQdtxcihcCI+ehDhyk+ZJ1C8gdx9QqJkMLUmLgG1U3jKRm94zDpXMDuu0HNlS5roJwgIyMCq/4RijamO6pjIaX+hQ0Q31JlC/JuguirBZb9NRK2xUmSMzNU3OZQcEi7pxyj00va/JMexhkuWuIS9myimI14hWUims2YPa6tb2tu6365otFpRC0ZY722UjV//o93PAOjj+kn6hSX+bToSJ0i1kUR44zrfH4G80moOiTDoqzD3ppBHyu5c/zdqvGrfmhdyvfB8t/EeXN4eD7dFR+wLLkQhVj8Tz8OTyrzAuvHkoOkMeUebVy3qkGxRgFQXqen57UrWskVywQdCWYu+2Vtp+Z581pppstED8e0UlfPNqCAQXGfasEGLobob+poyXWkCaJHxtHTmdqly29993qI6WA+jb7E5go9QQCzPK9ioSLcPaETVfCO8ZxftL8GG0/YP9CcL4KbyyZvOTpbtUvASYYuibDbUCJHVw=
      bucket: skillsforge-account-feed-utils
      local-dir: target/deploy
      upload-dir: jar
      acl: public_read
      region: eu-west-2
      on:
        tags: true
notifications:
  slack:
    secure: USn8MiAbMnu1H+FTAiG+acjsYBKUs7hNEme0Hp5NiuWWxN0D/ckJs1CTJa5isXrlsC8OEaeDjekWvs+NhwxQpOxQtPSKzftTTt8e6VV8+PDBLXnqiTpixCxahewoNqDSSuHGtHLVR5m6WYaSVutUciBSMnVvoBvY9Xns7Tx9gehPZh6uDd9L491zeeXHN6M+fQJUa21iYEdZHXoEJZ9bvgE12+k7pP0x0YrJCT39xjy3xS9cyn8YbkY5UVbe7G9wCgh2W1ZASOxGMaw2pIpNpihxJ9qFZDkW3E4XfnrBLu6QYAGdp77FBGxopkW+1XxzDHAFOuYflpUFrSpL4IW0kX3WLvY0va+NIq2TMgpWV7lTDIVS1HozrKV06XPssMox+/PEGlbtMVjF/o+4Bs2L50ydgjzILpC8U9cPmrt3waTMCCymX3nCXUhNHw9amTCOShZSHeCA//iEFS5z5tSA2pzIc39wxAyvJf6u8itRq5SSEKUUqllQ9mJvKF0ZnFzuEA5B/xKNBCGm22JWloCRNDzdPRFnI/uC7L7+Yk/oR6newze1XjYVvg44ESH4bfXdQdKP48od4ItKXE+7wqMZ7IFQgFAajq+h2fXAQpY97pLXNyassd0rT5XGBHXvYgMqJjeRe/3Y+GBVE4a+QR1b6PwdBYCupvVspWtX/P0peJE=
    on_success: always